//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinanzasPersonales
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoCorte
    {
        public int CorteID { get; set; }
        public System.DateTime Año { get; set; }
        public System.DateTime Mes { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public decimal BalanceInicial { get; set; }
        public decimal TotalIngresos { get; set; }
        public decimal TotalEgresos { get; set; }
        public decimal BalanceAlCorte { get; set; }
    }
}
