//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinanzasPersonales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int NoTransaccion { get; set; }
        public Nullable<int> TipoTransaccionID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string GastoOIngreso { get; set; }
        public Nullable<int> TipoPagoID { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal MontoTransaccion { get; set; }
        public string NoTarjetaCR { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual EstadoTransaccion EstadoTransaccion { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
