//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinanzasPersonales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public decimal LimiteEgreso { get; set; }
        public Nullable<int> TipoPersonaID { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public bool Estado { get; set; }
        public string NombreUsuario { get; set; }
        public string Clave { get; set; }
    
        public virtual TipoPersona TipoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
